name: C/C++ CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install zfsutils-linux build-dep cmake
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: make install
    - name: test run
      run: /bin/snapzap || true
