name: C/C++ CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    
    - name: install dependencies
      uses: tecolicom/actions-use-apt-tools@v1
      with: 
        tools: zfsutils-linux libzfslinux-dev build-essential cmake bats parallel ccache libhiredis1.1.0

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
    
    - name: build snapzap
      run: make
    
    - name: test snapzap install
      run: |
        make install
        /usr/local/bin/snapzap || true
    
    - name: run tests
      run: |
        cp build/snapzap ./
        export TERM=xterm-256color
        bats --jobs 5 --trace --verbose-run tests/
